booking/urls.py
from django.urls import path

from . import views

app_name = 'booking'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.ShowView.as_view(), name='show'),
]

sampleapp/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView

urlpatterns = [
    path('', RedirectView.as_view(url='booking/')),
    path('booking/', include('booking.urls')),
    path('admin/', admin.site.urls),
]

booking/models.py
from django.db import models

# We could make a Model with ResourceTypes and link it with a foreign key to Resources to allow admin to easily create new types.
class Resource(models.Model):
    class ResourceTypes(models.IntegerChoices):
        MEETING_ROOM = 1
        OPEN_SPACE = 2
        DESK = 3

    label = models.CharField(max_length=50)
    type = models.IntegerField(choices=ResourceTypes.choices, default=ResourceTypes.DESK)
    location = models.CharField(max_length=200)
    capacity = models.PositiveIntegerField()

    def __str__(self):
        return self.label

booking/views.py
from django.views import generic

from .models import Resource


class IndexView(generic.ListView):
    template_name = 'booking/index.html'

    def get_queryset(self):
        return Resource.objects.all()

class ShowView(generic.DetailView):
    model = Resource
    template_name = 'booking/show.html'

booking/templates/booking/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Resources</title>
  </head>
  <body>
    {% if resource_list %}
      <ul>
      {% for resource in resource_list %}
        <li><a href="{% url 'booking:show' resource.id %}">{{ resource.label }}</a></li>
      {% endfor %}
      </ul>
    {% else %}
      <p>No resources are available.</p>
    {% endif %}
  </body>
</html>

booking/templates/booking/show.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Resource</title>
    <link rel="stylesheet" type="text/css" href="{% static 'booking/style.css' %}">
  </head>
  <body>
    <h1>{{ resource.label }}</h1>
    <p>
      <u>Type:</u> {{ resource.get_type_display }}<br/>
      <u>Location:</u> {{ resource.location }}<br/>
      <u>Capacity:</u> {{ resource.capacity }}<br/>
    </p>
  </body>
</html>